#ifndef EXTERNAL_INTERRUPT_CFG_H
#define EXTERNAL_INTERRUPT_CFG_H

/*Possibilities of interrupt modes*/

/*INT0 MODES*/


/*YOU HAVE THESE OPTIONS TO CONFIGURE INT0
1)INT0_MODE_LOW_LEVEL_TRIGGER
2)INT0_MODE_FALLING_EDGE_TRIGGER
3) INT0_MODE_RISING_EDGE_TRIGGER
4) INT0_MODE_LOGICAL_CHANGE_TRIGGER
*/

/*INT1 MODES*/

/*YOU HAVE THESE OPTIONS TO CONFIGURE INT1
1)INT1_MODE_LOW_LEVEL_TRIGGER 
2)INT1_MODE_FALLING_EDGE_TRIGGER 
3) INT1_MODE_RISING_EDGE_TRIGGER 
4) INT1_MODE_LOGICAL_CHANGE_TRIGGER 
*/

/*INT2 MODES*/
/*YOU HAVE THESE OPTIONS TO CONFIGURE INT2
1)INT1_MODE_FALLING_EDGE_TRIGGER
2) INT1_MODE_RISING_EDGE_TRIGGER
*/


/*Configuration of External Interrupt Pins*/

#define EXTI_INT0_MODE INT0_MODE_FALLING_EDGE_TRIGGER
#define EXTI_INT1_MODE INT1_MODE_FALLING_EDGE_TRIGGER
#define EXTI_INT2_MODE INT2_MODE_FALLING_EDGE_TRIGGER


/*Pin Numbers of external interrupt registers*/

/*MCUCR Pins*/
/* CONFIGURE THE MODES OF INTERRUPTS*/
/*************************/


/*MCUCSR Pins*/
/*CONFIGURE INT2 MODE*/

#define MCUCSR_ISC2_PIN 6

/*GICR Pins */
/*ENABLE INTERRUPTS*/
#define GICR_INT0_PIN 6
#define GICR_INT1_PIN 7
#define GICR_INT2_PIN 5


/*GIFR Pins */
/*FLAG OF INTERRUPTS*/
#define GIFR_INT0_PIN 6
#define GIFR_INT1_PIN 7
#define GIFR_INT2_PIN 5

/*Enable and disable interrupts*/

#define ENABLE_INTERRUPT 0
#define DISABLE_INTERRUPT 1

/*Configure Status of each interrupt*/

#define EXTI_INT0_STATUS ENABLE_INTERRUPT
#define EXTI_INT1_STATUS ENABLE_INTERRUPT
#define EXTI_INT2_STATUS DISABLE_INTERRUPT
#endif