#ifndef EXTERNAL_INTERRUPT_PRV_H
#define EXTERNAL_INTERRUPT_PRV_H


#include "STD_Types.h"

#define MCUCR_REG *(volatile u8*)0x55
#define MCUCSR_REG *(volatile u8*)0x54
#define GICR_REG *(volatile u8*)0x5B
#define GIFR_REG *(volatile u8*)0x5A




/*INT0 MODES*/

#define INT0_MODE_LOW_LEVEL_TRIGGER 0b00
#define INT0_MODE_FALLING_EDGE_TRIGGER 0b10
#define INT0_MODE_RISING_EDGE_TRIGGER 0b11
#define INT0_MODE_LOGICAL_CHANGE_TRIGGER 0b01

/*INT1 MODES*/


#define INT1_MODE_LOW_LEVEL_TRIGGER 0b00
#define INT1_MODE_FALLING_EDGE_TRIGGER 0b10
#define INT1_MODE_RISING_EDGE_TRIGGER 0b11
#define INT1_MODE_LOGICAL_CHANGE_TRIGGER 0b01

/*INT2 MODES*/

#define INT2_MODE_FALLING_EDGE_TRIGGER 0
#define INT2_MODE_RISING_EDGE_TRIGGER 1


#endif 