#ifndef ADC_CFG_H
#define ADC_CFG_H

#define ADC_PRESCALER_2 0x1
#define ADC_PRESCALER_4 0x02
#define ADC_PRESCALER_8 0x03
#define ADC_PRESCALER_16 0x04
#define ADC_PRESCALER_32 0x05
#define ADC_PRESCALER_64 0x06
#define ADC_PRESCALER_128 0x07
#define ADC_PRESCALER ADC_PRESCALER_128
#define ADC_REFS_AREF_MASK 0x00
#define ADC_REFS_AVCC_MASK 0x40
#define ADC_REFS_INTERNAL_MASK 0xc0
#define ADC_REF_SELECTION ADC_REFS_AVCC_MASK
#define RESOLUTION_8_BIT 0
#define RESOLUTION_10_BIT 1
#define RESOLUTION_SELECTION RESOLUTION_8_BIT
#define POLLING_SELECTION 0
#define INTERRUPT_SELECTION 1
#define ENABLE 1
#define DISABLE 0
#define RIGHT_ADJUST ENABLE
#define LEFT_ADJUST DISABLE
#define AUTO_TRIGGER DISABLE
#define SELECT_POLLING_INTERRUPT  POLLING_SELECTION
#define FREE_RUNNING_TRIGGER 0x00
#define ANALOG_COMPARATOR_TRIGGER 0x20
#define EXTI_REQ0_TRIGGER 0x40
#define TIMER0_COMP_MATCH_TRIGGER 0x60
#define TIMER0_OVER_FLOW_TRIGGER 0x80
#define TIMER_COM_MATCH_B_TRIGGER 0xA0
#define TIMER1_OVER_FLOW 0xC0
#define TIMER1_CAPTURE_EVENT_TRIGGER 0xE0
#define AUTO_TRIGGER_SOURCE EXTI_REQ0_TRIGGER
#define TIME_OUT 2000
/*struct of ADC Chain*/
typedef struct  
{
	u8 length;
	u8 *Channels;
	u16 *Result;     /*Configurable*/
	void(*EOJ)(void); /*Notification Function*/
	
}ADC_CHAIN_t;
#endif 